---
title: "T20BLAST23"
output: html_document
date: "2023-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)




```



```{R}




library(jsonlite)

library(tidyverse)

library(tidymodels)
library(bonsai)

library(rjson)


```





```{R}


setwd("C:/Users/alext/OneDrive/Documents/data/t20")


fileread <- function(x) {
  data <- fromJSON(file = x)


  df <- enframe(unlist(data))


  rgx_split <- "\\."
  n_cols_max <-
    df %>%
    pull(name) %>%
    str_split(rgx_split) %>%
    map_dbl(~ length(.)) %>%
    max()



  nms_sep <- paste0("name", 1:n_cols_max)
  df_sep <-
    df %>%
    separate(name, into = nms_sep, sep = rgx_split, fill = "right")





  innr <- df_sep %>%
    filter(name1 == "innings") %>%
    mutate(team = if_else(name2 == "team", value, NA_character_)) %>%
    fill(team, .direction = "down") %>%
    mutate(over = if_else(name3 == "over", value, NA_character_)) %>%
    fill(over, .direction = "down") %>%
    mutate(bat = if_else(name4 == "batter", value, NA_character_)) %>%
    fill(bat, .direction = "down") %>%
    mutate(bowl = if_else(name4 == "bowler", value, NA_character_)) %>%
    fill(bowl, .direction = "down") %>%
    mutate(ns = if_else(name4 == "non_striker", value, NA_character_)) %>%
    fill(ns, .direction = "down") %>%
    mutate(bat_run = if_else(name5 == "batter", value, NA_character_)) %>%
    fill(bat_run, .direction = "down") %>%
    mutate(extras = if_else(name5 == "extras", value, NA_character_)) %>%
    mutate(wick = if_else(name5 == "kind", value, NA_character_)) %>%
    mutate(filt = if_else(!is.na(extras), extras,
      if_else(!is.na(wick), wick, NA_character_)
    )) %>%
    fill(filt, .direction = "up") %>%
    fill(extras, .direction = "down") %>%
    mutate(totrun = if_else(name5 == "total", value, NA_character_)) %>%
    filter(!is.na(totrun)) %>%
    select(team, over, bat, bowl, ns, bat_run, extras, totrun, filt) %>%
    mutate(file = x) %>%
    group_by(team, over, file) %>%
    mutate(over2 = as.numeric(as.character(over))) %>%
    mutate(ovball = 1:n()) %>%
    mutate(innball = over2 * 6 + ovball) %>%
    ungroup() %>%
    mutate(lagte = lag(team)) %>%
    mutate(inn = if_else(is.na(lagte), "1",
      if_else(lagte != team, "2", NA_character_)
    )) %>%
    fill(inn, .direction = "down") %>%
    select(-lagte)



  # d_test <- df %>% separate(name, into = c("n1", "n2", "n3", "n4", "n5", "n6", "n7", "n8"), fill = "right") %>%
  #                         filter(n1 == "info")  %>%
  #                        filter(n2 != "players") %>%
  #                       filter(n2 != "registry") %>%
  #                      filter(n3 != "group") %>%
  #                     filter(n2 != "officials") %>%
  #                    mutate(col2 = if_else(n3 == "winner", n3, n2)) %>%
  #                   mutate(col3 = if_else(col2 == "outcome", paste(n4, value), value)) %>%
  #                  mutate(col4 = if_else(col2 == "winner", paste(n2,n3, sep = "_"), col2)) %>%
  #                 select(col4,col3) %>%
  #                pivot_wider(names_from = col4, values_from = col3)  %>%
  #               select(-team)



  # innr2 <- innr %>% bind_cols(d_test)

  return(innr)
}





files <- list.files()

dataset2 <- map_dfr(files, fileread)









```





```{r}


setwd("C:/Users/alext/OneDrive/Documents/data/t20")

matchinfo <- function(x) {
  data <- fromJSON(file = x)


  df <- enframe(unlist(data))


  rgx_split <- "\\."
  n_cols_max <-
    df %>%
    pull(name) %>%
    str_split(rgx_split) %>%
    map_dbl(~ length(.)) %>%
    max()



  nms_sep <- paste0("name", 1:n_cols_max)
  df_sep <-
    df %>%
    separate(name, into = nms_sep, sep = rgx_split, fill = "right")



  df_info2 <- df_sep %>%
    filter(name1 == "info") %>%
    filter(name2 != "players") %>%
    #  filter(name2 != "registry") %>%
    # filter(name2 != "officials") %>%
    #  filter(value != "D/L") %>%
    # mutate(col2 = if_else(name2 == "event", name3, name2)) %>%
    #    filter(col2 != "group") %>%
    # mutate(col4 = if_else(col2 == "outcome", if_else(name3 == "winner", "outcome_t", "outcome_m"), col2)) %>%
    #  mutate(col5 = if_else(col4 == "name", "comp", col4)) %>%
    #   mutate(col6 = if_else(col5 == "toss", if_else(name3 == "decision", "toss_d", "toss_w"), col5)) %>%
    #   mutate(col7 = if_else(col6 == "outcome_m", paste(name4, value, sep = "-"), value)) %>%
    #    filter(col6 != "balls_per_over") %>%
    # select(col6,col7) %>%
    # pivot_wider(names_from = col6, values_from = col7)  %>%
    mutate(file = x)

  return(df_info2)
}








setwd("C:/Users/alext/OneDrive/Documents/data/t20")

extr_count <- function(x) {
  data <- fromJSON(file = x)


  df <- enframe(unlist(data))


  rgx_split <- "\\."
  n_cols_max <-
    df %>%
    pull(name) %>%
    str_split(rgx_split) %>%
    map_dbl(~ length(.)) %>%
    max()



  nms_sep <- paste0("name", 1:n_cols_max)
  df_sep <-
    df %>%
    separate(name, into = nms_sep, sep = rgx_split, fill = "right")


  innr_extra <- df_sep %>%
    filter(name1 == "innings") %>%
    mutate(team = if_else(name2 == "team", value, NA_character_)) %>%
    fill(team, .direction = "down") %>%
    filter(name4 == "extras") %>%
    filter(name5 %in% c("noballs", "wides")) %>%
    ungroup() %>%
    group_by(team) %>%
    summarise(n = n()) %>%
    mutate(file = x)



3


  return(innr_extra)
}


files <- list.files()

match_etras <- map_dfr(files, extr_count)



setwd("C:/Users/alext/OneDrive/Documents/data/t20")


play_list <- function(x) {
  data <- fromJSON(file = x)


  df <- enframe(unlist(data))


  rgx_split <- "\\."
  n_cols_max <-
    df %>%
    pull(name) %>%
    str_split(rgx_split) %>%
    map_dbl(~ length(.)) %>%
    max()



  nms_sep <- paste0("name", 1:n_cols_max)
  df_sep <-
    df %>%
    separate(name, into = nms_sep, sep = rgx_split, fill = "right")





  df_play <- df_sep %>%
    filter(name2 == "players") %>%
    mutate(no = parse_number(name3)) %>%
    mutate(team = if_else(no < 10, str_sub(name3, 1, nchar(name3) - 1), str_sub(name3, 1, nchar(name3) - 2))) %>%
    select(team, no, value) %>%
    mutate(file = x)


  colnames(df_play)[3] <- "player"




  return(df_play)
}


files <- list.files()

match_play <- map_dfr(files, play_list)


setwd("C:/Users/alext/OneDrive/Documents/data/t20")



files <- list.files()

infos <- map_dfr(files, matchinfo)


````



```{r}


date <- infos %>%
  filter(grepl("dates", name2)) %>%
  group_by(file) %>%
  mutate(fil = 1:n()) %>%
  filter(fil == 1) %>%
  select(value, file)

colnames(date)[1] <- "Match_dat"

event <- infos %>%
  filter(name2 == "event") %>%
  filter(name3 == "name") %>%
  select(value, file)

colnames(event)[1] <- "comp"



gender <- infos %>%
  filter(name2 == "gender") %>%
  select(value, file)


colnames(gender)[1] <- "gen"




outcome_by <- infos %>%
  filter(name2 == "outcome") %>%
  filter(name3 == "by") %>%
  select(name4, value, file)


colnames(outcome_by)[1] <- "Outmeas"
colnames(outcome_by)[2] <- "Outval"


outcome_by2 <- infos %>%
  filter(name2 == "outcome") %>%
  filter(name3 %in% c("bowl_out", "eliminator", "winner")) %>%
  select(value, file)


colnames(outcome_by2)[1] <- "winning_team"


toss_d <- infos %>%
  filter(name2 == "toss") %>%
  filter(name3 == "decision") %>%
  select(value, file)

colnames(toss_d)[1] <- "td"

toss_w <- infos %>%
  filter(name2 == "toss") %>%
  filter(name3 == "winner") %>%
  select(value, file)


colnames(toss_w)[1] <- "tw"



venue <- infos %>%
  filter(name2 == "venue") %>%
  select(value, file)

colnames(venue)[1] <- "ground"

colnames(teams)[1] <- "tw"

colnames(teams)[3] <- "comp_t"



info2 <- date %>%
  left_join(event, by = "file") %>%
  left_join(gender, by = "file") %>%
  left_join(outcome_by, by = "file") %>%
  left_join(outcome_by2, by = "file") %>%
  left_join(toss_d, by = "file") %>%
  left_join(toss_w, by = "file") %>%
  left_join(venue, by = "file") %>%
  left_join(teams, by = "tw")






all_dat <- dataset2 %>% left_join(info2, by = "file")



dat2 <- all_dat %>%
  group_by(team, file) %>%
  mutate(ball2 = row_number()) %>%
  ungroup() %>%
  separate(Match_dat, c("yy", "mm", "dd"), sep = "-") %>%
  select(-mm, -dd) %>%
  mutate(bat_run = as.numeric(as.character(bat_run)), extras = as.numeric(as.character(extras)), as.numeric(as.character(bat_run)), totrun = as.numeric(as.character(totrun)))

dat2$yy <- as.numeric(as.character(dat2$yy))





````






```{r}



vitality_blast <- fin_dat %>%
  filter(comp == "Vitality Blast") %>%
  filter(yy == 2023)



vital_bat <- vitality_blast %>%
  group_by(bat) %>%
  mutate(batr = as.numeric(as.character(bat_run))) %>%
  summarise(totwpa = sum(batdelt, na.rm = T) * 100, n = n() / 10, tr = sum(batr), ball = n()) %>%
  mutate(wpa10 = totwpa / n)





vitality_blast_years <- fin_dat %>%
  filter(comp == "Vitality Blast") %>%
    group_by(bat, yy) %>%
  mutate(batr = as.numeric(as.character(bat_run))) %>%
  summarise(totwpa = sum(batdelt, na.rm = T) * 100, n = n() / 10, tr = sum(batr), ball = n()) %>%
  mutate(wpa10 = totwpa / n)








```



```{r}





best_ball = vitality_blast %>% group_by(bat, file) %>%
                                    mutate(ibal = 1:n()) %>%
                                        ungroup() %>%
                                            group_by(bat, ibal) %>%
                                                summarise(tot = mean(batdelt, na.rm = T), n = n())





play_comp = best_ball %>% filter(bat %in% c("SR Hain", "WCF Smeed", "MS Pepper", "JM Vince")) %>%
                                    ungroup() %>%
                                      group_by(bat) %>%
                                        mutate(cumlat = cumsum(tot))



ggplot(play_comp, aes(x = ibal, y = cumlat, col = bat)) + geom_line() 

```




```{r}



best_period = vitality_blast %>%
                                mutate(gamepoint = if_else(ball2 < 37, "Power Play", 
                                                           if_else(ball2 > 90, "Death", "Middle"))) %>%
                                         ungroup() %>%
                                             group_by(bat, file) %>%
                                    mutate(ibal = 1:n()) %>%
                                        ungroup() %>%
                                              mutate(innstart = if_else(ibal == 1, gamepoint, NA)) %>%
                                                group_by(bat, file) %>%
                                                fill(innstart, .direction = "down") %>%
                                                      ungroup() %>%
                                                  group_by(bat, gamepoint, innstart) %>%
                                                          summarise(totbat = sum(batdelt, na.rm = T), n = n()) %>%
                                                            mutate(wpa10 = totbat/n*10)








```




```{r}






death_bat = best_period %>%
                          filter(gamepoint == "Death") %>%
                              filter(wpa10 > -0.25)



ggplot(death_bat, aes(x = innstart, y = wpa10, size = n, label = bat)) + geom_jitter()



```



```{r}


blast_play  = match_play %>% left_join(info2, by = "file") %>%
                                    filter(comp == "Vitality Blast") %>%
                                        separate(Match_dat, into = c("yy", "mm", "dd"), sep = "-") %>%
                                          filter(yy == 2023) %>%
                                              group_by(team, player) %>%
                                                summarise(n = n()) %>%
                                      left_join(t20blast_statsv4, by = "player") %>%
                                            select(team, player, tot_bat_wp, wpa6, n, bpi) %>%
                                                  ungroup() %>%
                                                    group_by(team) %>%
                                                      mutate(rankl  = rank(desc(n))) %>%
                                                    filter(rankl < 12)
















```



```{r}


team2_bat = blast_play %>%
                              group_by(team) %>%
                              mutate(batrank = rank(desc(tot_bat_wp)))  %>%
                                  filter(batrank < 8) %>%
                                     filter(batrank < 8) %>%
                                      mutate(coltit = if_else(batrank == 1, "bat_1",
                                                              if_else(batrank == 2, "bat_2",
                                                                if_else(batrank == 3, "bat_3",
                                                                  if_else(batrank == 4, "bat_4",
                                                 if_else(batrank == 5, "bat_5",
                                                         if_else(batrank == 6, "bat_6",
                                                          if_else(batrank == 7, "bat_7", "brgrf")))))))) %>%
                        
                                          select(team, coltit, tot_bat_wp) %>%
                                      pivot_wider(names_from = coltit, values_from = tot_bat_wp)




team2_bowl = blast_play %>%
                              group_by(team) %>%
                              mutate(bowlrank = rank(desc(bpi)))  %>%
                                filter(bowlrank < 6) %>%
                                  mutate(bowlr = rank(desc(wpa6))) %>%
                                    select(bowlr, wpa6) %>%
                                      mutate(coltit = if_else(bowlr == 1, "bowl_1",
                                                              if_else(bowlr == 2, "bowl_2",
                                                                if_else(bowlr == 3, "bowl_3",
                                                                  if_else(bowlr == 4, "bowl_4",
                                                 if_else(bowlr == 5, "bowl_5", "Rr")))))) %>%
                        
                                          select(team, coltit, wpa6) %>%
                                      pivot_wider(names_from = coltit, values_from = wpa6)

group = c("North", "North", "North", "South", "South", "South", "South", "South", "North", "North", "South", "North", "North", "South", "South", "South", "North", "North")



teamo = team2_bat %>% select(team) %>%
                            ungroup() %>%
                            mutate(teamno = 1:n()) %>%
                              rename(opteam = team) %>%
                                bind_cols(group) 


colnames(teamo)[3] = "group"



teamo2 = teamo %>% select(opteam, group) %>%
                          rename(team = opteam, teamgr = group)



team2_batop = blast_play %>%
                              group_by(team) %>%
                              mutate(batrank = rank(desc(tot_bat_wp)))  %>%
                                  filter(batrank < 8) %>%
                                     filter(batrank < 8) %>%
                                      mutate(coltit = if_else(batrank == 1, "opbat_1",
                                                              if_else(batrank == 2, "opbat_2",
                                                                if_else(batrank == 3, "opbat_3",
                                                                  if_else(batrank == 4, "opbat_4",
                                                 if_else(batrank == 5, "opbat_5",
                                                         if_else(batrank == 6, "opbat_6",
                                                          if_else(batrank == 7, "opbat_7", "brgrf")))))))) %>%
                        
                                          select(team, coltit, tot_bat_wp) %>%
                                      pivot_wider(names_from = coltit, values_from = tot_bat_wp)




team2_bowlop = blast_play %>%
                              group_by(team) %>%
                              mutate(bowlrank = rank(desc(bpi)))  %>%
                                filter(bowlrank < 6) %>%
                                  mutate(bowlr = rank(desc(wpa6))) %>%
                                    select(bowlr, wpa6) %>%
                                      mutate(coltit = if_else(bowlr == 1, "OPbowl_1",
                                                              if_else(bowlr == 2, "OPbowl_2",
                                                                if_else(bowlr == 3, "OPbowl_3",
                                                                  if_else(bowlr == 4, "OPbowl_4",
                                                 if_else(bowlr == 5, "OPbowl_5", "Rr")))))) %>%
                        
                                          select(team, coltit, wpa6) %>%
                                      pivot_wider(names_from = coltit, values_from = wpa6)




team_sumop = team2_batop %>% left_join(team2_bowlop, by = "team") %>%
                              rename(opteam = team)




team_sum = team2_bat %>% left_join(team2_bowl, by = "team") %>%
                              mutate(opp_team = 18) %>%
                                uncount(opp_team) %>%
                                    group_by(team) %>%
                                        mutate(teamno = 1:n()) %>%
                                           left_join(teamo, by = "teamno") %>%
                                              left_join(team_sumop, by = "opteam") %>%
                                      mutate(fil = if_else(team==opteam, 1,0)) %>%
                                          filter(fil == 0) %>%
                                            left_join(teamo2, by = "team")





preds =  predict(fin_fitv4, team_sum, type = "prob")


team_sum2 = team_sum %>% bind_cols(preds) %>%
                              mutate(win = if_else(.pred_Yes > 0.5, 2,0)) %>%
                                group_by(team) %>%
                                  summarise(tot = sum(win), mewi = mean(.pred_Yes))




team_sum2_north = team_sum %>% bind_cols(preds) %>%
                              mutate(win = if_else(.pred_Yes > 0.5, 2,0)) %>%
                                  filter(group == "North") %>%
                                    filter(teamgr == "North") %>%
                                       group_by(team) %>%
                                  summarise(tot = sum(win), mewi = mean(.pred_Yes))


team_sum2_south = team_sum %>% bind_cols(preds) %>%
                              mutate(win = if_else(.pred_Yes > 0.5, 2,0)) %>%
                                  filter(group == "South") %>%
                                   filter(teamgr == "South") %>%
                                       group_by(team) %>%
                                  summarise(tot = sum(win), mewi = mean(.pred_Yes))



```




```{r}




wood = fin_dat %>% filter(comp == "Vitality Blast") %>%
                          group_by(bowl, file, yy) %>%
                              summarise(totbow = sum(bowldelt, na.rm = T), n = n()) %>%
                                mutate(wpa6 = totbow/(n/6)) %>%
                                  filter(bowl == "NA Sowter")



ggplot(wood, aes(x = yy, y = wpa6, group = yy)) + geom_boxplot()








```




```{r}


all_bowl = fin_dat %>% filter(comp == "Vitality Blast") %>%
                          group_by(bowl, file, yy) %>%
                              summarise(totbow = sum(bowldelt, na.rm = T), n = n()) %>%
                                mutate(wpa6 = totbow/(n/6)) %>%
                                    filter(n > 11)


ggplot(all_bowl, aes(x = wpa6)) + geom_histogram()






```




```{r}


all_bowl = fin_dat %>% filter(comp == "Vitality Blast") %>%
                          filter(yy == 2023) %>%
                                ungroup() %>%
                                 group_by(bowl) %>%
                                  summarise(totbow = sum(bowldelt, na.rm = T), n = n()) %>%
                                mutate(wpa6 = totbow/(n/6)) 
                            










```


###### ipl 

```{r}


ipl_play  = match_play %>% left_join(info2, by = "file") %>%
                                    filter(comp == "Indian Premier League") %>%
                                        separate(Match_dat, into = c("yy", "mm", "dd"), sep = "-") %>%
                                          filter(yy == 2023) %>%
                                              group_by(team, player) %>%
                                                summarise(n = n()) %>%
                                            left_join(ipl_statsv4, by = "player") %>%
                                            select(team, player, tot_bat_wp, wpa6, n, bpi) %>%
                                                  ungroup() %>%
                                                    group_by(team) %>%
                                                      mutate(rankl  = rank(desc(n))) %>%
                                                    filter(rankl < 12)





```



```{r}


team2_bat = ipl_play %>%
                              group_by(team) %>%
                              mutate(batrank = rank(desc(tot_bat_wp)))  %>%
                                  filter(batrank < 8) %>%
                                     filter(batrank < 8) %>%
                                      mutate(coltit = if_else(batrank == 1, "bat_1",
                                                              if_else(batrank == 2, "bat_2",
                                                                if_else(batrank == 3, "bat_3",
                                                                  if_else(batrank == 4, "bat_4",
                                                 if_else(batrank == 5, "bat_5",
                                                         if_else(batrank == 6, "bat_6",
                                                          if_else(batrank == 7, "bat_7", "brgrf")))))))) %>%
                        
                                          select(team, coltit, tot_bat_wp) %>%
                                      pivot_wider(names_from = coltit, values_from = tot_bat_wp)




team2_bowl = ipl_play %>%
                              group_by(team) %>%
                              mutate(bowlrank = rank(desc(bpi)))  %>%
                                filter(bowlrank < 6) %>%
                                  mutate(bowlr = rank(desc(wpa6))) %>%
                                    select(bowlr, wpa6) %>%
                                      mutate(coltit = if_else(bowlr == 1, "bowl_1",
                                                              if_else(bowlr == 2, "bowl_2",
                                                                if_else(bowlr == 3, "bowl_3",
                                                                  if_else(bowlr == 4, "bowl_4",
                                                 if_else(bowlr == 5, "bowl_5", "Rr")))))) %>%
                        
                                          select(team, coltit, wpa6) %>%
                                      pivot_wider(names_from = coltit, values_from = wpa6)






```


```{r}



team2_batop = ipl_play %>%
                              group_by(team) %>%
                              mutate(batrank = rank(desc(tot_bat_wp)))  %>%
                                  filter(batrank < 8) %>%
                                     filter(batrank < 8) %>%
                                      mutate(coltit = if_else(batrank == 1, "opbat_1",
                                                              if_else(batrank == 2, "opbat_2",
                                                                if_else(batrank == 3, "opbat_3",
                                                                  if_else(batrank == 4, "opbat_4",
                                                 if_else(batrank == 5, "opbat_5",
                                                         if_else(batrank == 6, "opbat_6",
                                                          if_else(batrank == 7, "opbat_7", "brgrf")))))))) %>%
                        
                                          select(team, coltit, tot_bat_wp) %>%
                                      pivot_wider(names_from = coltit, values_from = tot_bat_wp)




team2_bowlop = ipl_play %>%
                              group_by(team) %>%
                              mutate(bowlrank = rank(desc(bpi)))  %>%
                                filter(bowlrank < 6) %>%
                                  mutate(bowlr = rank(desc(wpa6))) %>%
                                    select(bowlr, wpa6) %>%
                                      mutate(coltit = if_else(bowlr == 1, "OPbowl_1",
                                                              if_else(bowlr == 2, "OPbowl_2",
                                                                if_else(bowlr == 3, "OPbowl_3",
                                                                  if_else(bowlr == 4, "OPbowl_4",
                                                 if_else(bowlr == 5, "OPbowl_5", "Rr")))))) %>%
                        
                                          select(team, coltit, wpa6) %>%
                                      pivot_wider(names_from = coltit, values_from = wpa6)




team_sumop_ipl = team2_batop %>% left_join(team2_bowlop, by = "team") %>%
                              rename(opteam = team)














```


```{r}


team_sum = team2_bat %>% left_join(team2_bowl) 


teams_ipl = team_sum %>%
                      select(team) %>%
                            ungroup() %>%
                            mutate(teamno = 1:n())
 



team_sum2 = team_sum %>% ungroup() %>%
                            mutate(n = 10) %>%
                              uncount(n) %>%
                               group_by(team) %>%
                                  mutate(teamno = 1:n()) %>%
                                    left_join(teams_ipl, by = "teamno") %>%
                                rename(opteam = team.y) %>%
                              left_join(team_sumop_ipl, by = "opteam") %>%
                              mutate(fil = if_else(team.x == opteam, 1,0)) %>%
                                filter(fil == 0)
 


match_pred = predict(fin_fitv4, team_sum2, type = "prob")


team_sum3  = team_sum2 %>% bind_cols(match_pred)  


```



```{r}




team_match = fin_dat %>% select(file, team) %>%
                              distinct(team) %>%
                                  group_by(file) %>%
                                      mutate(teamno = 1:n()) %>%
                                          mutate(nerrr = if_else(teamno == 1, "team.x", "opteam")) %>%
                                              ungroup() %>%
                                                select(-teamno) %>%
                                            pivot_wider(names_from = nerrr, values_from = team) %>%
                                              left_join(info2, by = "file") %>%
                                                  mutate(date = Match_dat) %>%
                                          separate(date, into = c("yy", "mm", "DD")) %>%
                                              filter(yy == 2023)
  

team_sum4 = team_sum3 %>% left_join(team_match, by = c("team.x", "opteam"))



```