---
title: "the100"
output: html_document
date: "2023-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}


library(tidyverse)


```

```{r}

na_check = vital_bat %>% filter(is.na(comp_fin)) %>%
                              group_by(comp) %>%
                                summarise(n = n())



na_check2 = fin_dat %>% group_by(comp) %>%
                              summarise(n = n())



na_check3 = vital_bat %>% filter(is.na(comp_t2))



```

```{r} 

match_teams = fin_dat %>% 
                              slice_min(innball) %>%
                                select(team, file) %>%
                                    group_by(file) %>%
                                        mutate(team3 = 1:n()) %>%
                                            mutate(teamtext = if_else(team3 == 1, "team1", "team2")) %>%
                                                select(-team3) %>%
                                                pivot_wider(names_from = teamtext, values_from = team) %>%
                    mutate(elite1 = if_else(team1 %in% c("India", "England", "New Zealand", "Pakistan", "Australia", 
                                                     "South Africa", "West Indies", "Sri Lanka", "Bangladesh", "West Indies", "Ireland","Afghanistan"), 1,0)) %>%
                                          mutate(elite2 = if_else(team2 %in% c("India", "England", "New Zealand", "Pakistan", "Australia", 
                                                     "South Africa", "West Indies", "Sri Lanka", "Bangladesh", "West Indies", "Afghanistan","Ireland"),1,0)) %>%
                                      mutate(elitetot = elite1 + elite2) %>%
                                             mutate(matcht = if_else(elitetot == 2, "elite", "other")) %>%
                                                select(file, matcht)






```


```{r}

test_dom = fin_dat %>% filter(comp_t == "Domestic") %>% 
                                group_by(team) %>% 
                                    summarise(n = n())






```


```{r}




vital_bat <- fin_dat %>% mutate(comp_t2 = if_else(is.na(comp_t), 
            if_else(comp %in% c("Syed Mushtaq Ali Trophy", "Bangladesh Premier League"), "Domestic", "International"), comp_t)) %>%
               mutate(comp_fin = if_else(comp_t2 == "International", "international", comp)) %>%
                 mutate(comp_fin2 = if_else(comp_fin == "NatWest T20 Blast", "Vitality Blast", comp_fin)) %>%
                    mutate(comp_fin2a = comp_fin2) %>%
                    separate(comp_fin2, into = c("x1", "x2", "x3", "x4"), sep = " ") %>%
                     mutate(comp_fin3 =   if_else(x1 == "ICC", "international", comp_fin2a)) %>%
                       left_join(match_teams, by = "file") %>%
                          mutate(comp_fin4 = if_else(matcht == "elite", "elite internation", comp_fin3)) %>%
  group_by(bat, comp_fin4, gen) %>%
  mutate(batr = as.numeric(as.character(bat_run))) %>%
  summarise(totwpa = sum(batdelt, na.rm = T) * 100, n = n() / 10, tr = sum(batr), ball = n()) %>%
  mutate(wpa10 = totwpa / n)  %>%
  ungroup() 



```



```{r}




com_test = vital_bat %>% ungroup() %>% 
                              group_by(comp_fin4) %>% 
                                      summarise(n = n())


com_test




```




```{r}




bat_sum_in = fin_dat %>% mutate(comp_t2 = if_else(is.na(comp_t), 
            if_else(comp %in% c("Syed Mushtaq Ali Trophy", "Bangladesh Premier League"), "Domestic", "International"), comp_t)) %>%
               mutate(comp_fin = if_else(comp_t2 == "International", "international", comp)) %>%
                 mutate(comp_fin2 = if_else(comp_fin == "NatWest T20 Blast", "Vitality Blast", comp_fin)) %>%
                    mutate(comp_fin2a = comp_fin2) %>%
                    separate(comp_fin2, into = c("x1", "x2", "x3", "x4"), sep = " ") %>%
                     mutate(comp_fin3 =   if_else(x1 == "ICC", "international", comp_fin2a)) %>%
                       left_join(match_teams, by = "file") %>%
                          mutate(comp_fin4 = if_else(matcht == "elite", "elite internation", comp_fin3)) %>%
                            group_by(file, bat) %>%
                              mutate(face_b = 1:n()) %>%
                                mutate(inper = if_else(face_b < 6, "early", "rest")) %>%
                                     group_by(bat,inper, comp_fin4, gen) %>%
                                 summarise(totwpa = sum(batdelt, na.rm = T) * 100, n = n() / 10, ball = n()) %>%
                                mutate(wpa10 = totwpa / n) %>%
                                      select(bat, gen, inper, comp_fin4, wpa10) %>%
                                          pivot_wider(names_from = inper, values_from = wpa10) %>%
                                                  rename(early_wpa10 = early, rest_wpa10 = rest)







````



```{r}




bat_sum_ga = fin_dat %>% mutate(comp_t2 = if_else(is.na(comp_t), 
            if_else(comp %in% c("Syed Mushtaq Ali Trophy", "Bangladesh Premier League"), "Domestic", "International"), comp_t)) %>%
               mutate(comp_fin = if_else(comp_t2 == "International", "international", comp)) %>%
                 mutate(comp_fin2 = if_else(comp_fin == "NatWest T20 Blast", "Vitality Blast", comp_fin)) %>%
                    mutate(comp_fin2a = comp_fin2) %>%
                    separate(comp_fin2, into = c("x1", "x2", "x3", "x4"), sep = " ") %>%
                     mutate(comp_fin3 =   if_else(x1 == "ICC", "international", comp_fin2a)) %>%
                       left_join(match_teams, by = "file") %>%
                          mutate(comp_fin4 = if_else(matcht == "elite", "elite internation", comp_fin3)) %>%
                                mutate(gameper = if_else(innball < 37, "powerplay", 
                                                         if_else(innball > 90, "death", "mid"))) %>%
                                     group_by(bat,gameper, comp_fin4, gen) %>%
                                 summarise(totwpa = sum(batdelt, na.rm = T) * 100, n = n() / 10, ball = n()) %>%
                                mutate(wpa10 = totwpa / n) %>%
                                      select(bat, gameper, comp_fin4, gen, wpa10) %>%
                                          pivot_wider(names_from = gameper, values_from = wpa10) %>%
                                                  rename(pp_wpa10 = powerplay, death_wpa10 = death, mid_wpa = mid)
 












```




```{r}


bat_stat <- fin_dat %>% mutate(comp_t2 = if_else(is.na(comp_t), 
            if_else(comp %in% c("Syed Mushtaq Ali Trophy", "Bangladesh Premier League"), "Domestic", "International"), comp_t)) %>%
               mutate(comp_fin = if_else(comp_t2 == "International", "international", comp)) %>%
                 mutate(comp_fin2 = if_else(comp_fin == "NatWest T20 Blast", "Vitality Blast", comp_fin)) %>%
                    mutate(comp_fin2a = comp_fin2) %>%
                    separate(comp_fin2, into = c("x1", "x2", "x3", "x4"), sep = " ") %>%
                     mutate(comp_fin3 =   if_else(x1 == "ICC", "international", comp_fin2a)) %>%
                       left_join(match_teams, by = "file") %>%
                          mutate(comp_fin4 = if_else(matcht == "elite", "elite internation", comp_fin3)) %>%
  group_by(bat, comp_fin4, gen) %>%
  mutate(batr = as.numeric(as.character(bat_run))) %>%
                        summarise(totrun = sum(batr), totballs = n())




bat_match = fin_dat %>% mutate(comp_t2 = if_else(is.na(comp_t), 
            if_else(comp %in% c("Syed Mushtaq Ali Trophy", "Bangladesh Premier League"), "Domestic", "International"), comp_t)) %>%
               mutate(comp_fin = if_else(comp_t2 == "International", "international", comp)) %>%
                 mutate(comp_fin2 = if_else(comp_fin == "NatWest T20 Blast", "Vitality Blast", comp_fin)) %>%
                    mutate(comp_fin2a = comp_fin2) %>%
                    separate(comp_fin2, into = c("x1", "x2", "x3", "x4"), sep = " ") %>%
                     mutate(comp_fin3 =   if_else(x1 == "ICC", "international", comp_fin2a)) %>%
                       left_join(match_teams, by = "file") %>%
                          mutate(comp_fin4 = if_else(matcht == "elite", "elite internation", comp_fin3)) %>%
  group_by(bat, file, comp_fin4, gen) %>%
                            summarise(n = n()) %>%
                                ungroup() %>%
                                  group_by(bat, comp_fin4) %>%
                              summarise(inns = n())
 



bat_stat2 = bat_stat %>% left_join(bat_match, by = c("bat", "comp_fin4")) %>%
                              mutate(bpi = totballs/inns, rpi = totrun/inns) %>%
                                  select(bat, comp_fin4, bpi, rpi, gen)









```



```{r}




player_list_bat = fin_dat %>% group_by(bat, file, gen) %>%
                              summarise(n =n()) %>%
                                ungroup() %>%
                                    distinct(bat) %>%
                             rename(player = bat)



player_list_bowl = fin_dat %>% group_by(bowl, file, gen) %>%
                                 summarise(n =n()) %>%
                                ungroup() %>%
                                    distinct(bowl) %>%
                             rename(player = bowl)

player_list_bat2 = fin_dat %>%
                             group_by(bat) %>%
                                summarise(bf = n()) %>%
                                  rename(player = bat)


player_list_bowl2 = fin_dat %>%
                             group_by(bowl) %>%
                                summarise(bb = n()) %>%
                                  rename(player = bowl)



player_list_gen = fin_dat %>% group_by(bat, gen) %>%
                              summarise(n =n()) %>%
                                ungroup()  %>%
                                  rename(player = bat) %>% 
                                    select(player, gen)





player_list =  player_list_bat %>%
                          bind_rows(player_list_bowl) %>%
                          distinct(player) %>%
                              left_join(player_list_bat2, by = c("player")) %>%
                                left_join(player_list_bowl2, by = c("player"))  %>%
                                   mutate(bb2= replace_na(bb, 0), bf2 = replace_na(bf, 0)) %>%
                                    mutate(tot = bb2 + bf2) %>%
                                      mutate(per_bat = bf/tot, per_bowl = bb/tot) %>%
                              mutate(position = if_else(per_bat > 0.7, "batter", 
                                                        if_else(per_bowl > 0.7, "bowler", "all rounder"))) %>%
                                    left_join(player_list_gen, by = "player") %>% 
                                  select(player, position, gen)









```








```{r}

player_listb = player_list %>%
                            rename(bat = player) 

bat_kpi = vital_bat %>% left_join(bat_sum_in, by = c("bat", "comp_fin4", "gen")) %>%
                            left_join(bat_sum_ga, by = c("bat", "comp_fin4", "gen")) %>%
                                left_join(bat_stat2, by = c("bat", "comp_fin4", "gen")) %>%
                                      left_join(player_listb, by = "bat", "gen") %>%
                                    group_by(comp_fin4, position, gen.x) %>%
                                    mutate(wpa10per = percent_rank(wpa10), eawpaper = percent_rank(early_wpa10), 
                                           restwpaper = percent_rank(rest_wpa10), ppper = percent_rank(pp_wpa10), 
                                           mid_per = percent_rank(mid_wpa), death_per = percent_rank(death_wpa10), 
                                           bpi_per = percent_rank(bpi), rpi_per = percent_rank(rpi)) %>%
                              select(bat, comp_fin4, gen.x, wpa10per, eawpaper, restwpaper, ppper, mid_per, death_per, bpi_per, rpi_per) %>%
                                            pivot_longer(cols = 5:12, names_to = "kpi", values_to = "percent") 





player = bat_kpi %>% filter(bat %in% c("WCF Smeed", "A Lyth", "PD Salt", "J Clark", "WG Jacks", "AM Rossington"))%>%
                          filter(comp_fin4 == "Vitality Blast")




ggplot(player, aes(x = kpi, y = percent, col = bat)) + geom_point()








player2 = bat_kpi %>% filter(bat %in% c("Shubman Gill", "DP Conway", "RG Sharma"))%>%
                          filter(comp_fin4 == "Indian Premier League")




ggplot(player2, aes(x = kpi, y = percent, col = bat)) + geom_point()









```






```{r}



bat_kpi_max = vital_bat %>% left_join(bat_sum_in, by = c("bat", "comp_fin4")) %>%
                            left_join(bat_sum_ga, by = c("bat", "comp_fin4")) %>%
                                left_join(bat_stat2, by = c("bat", "comp_fin4")) %>%
                                      left_join(player_listb, by = "bat") %>%
                                          group_by(comp_fin4, position) %>%
                                            mutate(percentile_wpa10 = percent_rank(wpa10), early_wpa10per = percent_rank(early_wpa10), 
                                                rest_wpa10per = percent_rank(rest_wpa10), mid_wpa10per = percent_rank(mid_wpa),
                                                death_wpa10per = percent_rank(death_wpa10), pp_wpa10per = percent_rank(pp_wpa10), 
                                                bpi_per = percent_rank(bpi), rpi_per = percent_rank(rpi))







play_sum = bat_kpi_max %>% 
                            filter(bat == "WCF Smeed") %>%
                                filter(comp_fin4 == "Vitality Blast") %>%
                           select(bat, comp_fin4, position, wpa10, early_wpa10, rest_wpa10, mid_wpa, death_wpa10, pp_wpa10, bpi, rpi) %>%
                                      pivot_longer(cols = 4:11, names_to = "stat", values_to = "meas")




play_sum2 = bat_kpi_max %>% 
                            filter(bat == "WCF Smeed") %>%
                                filter(comp_fin4 == "Vitality Blast") %>%
                           select(bat, comp_fin4, position, percentile_wpa10, early_wpa10per, rest_wpa10per, mid_wpa10per, death_wpa10per, pp_wpa10per, bpi_per, rpi_per) %>%
                                  rename( wpa10 = percentile_wpa10, early_wpa10 = early_wpa10per, rest_wpa10 = rest_wpa10per, mid_wpa = mid_wpa10per, death_wpa10 = death_wpa10per, pp_wpa10 = pp_wpa10per, bpi = bpi_per, rpi = rpi_per) %>%
                                      pivot_longer(cols = 4:11, names_to = "stat", values_to = "percentile") 






play_sum3 = play_sum %>% left_join(play_sum2, by = c( "stat", "comp_fin4", "bat", "position")) %>%
                                          





 



```





```{r}



max_val1 = vital_bat %>% left_join(bat_sum_in, by = c("bat", "comp_fin4")) %>%
                            left_join(bat_sum_ga, by = c("bat", "comp_fin4")) %>%
                                left_join(bat_stat2, by = c("bat", "comp_fin4")) %>%
                                      left_join(player_listb, by = "bat") %>%
                                          group_by(comp_fin4, position) %>%
         select(bat, comp_fin4, wpa10, early_wpa10, rest_wpa10, mid_wpa, death_wpa10, pp_wpa10, bpi, rpi, position) %>% 
                    pivot_longer(cols = 3:10, names_to = "kpis", values_to = "meas")  %>% 
                                              ungroup() %>% 
                                                group_by(comp_fin4, position, kpis) %>% 
                                                  slice_max(meas)












```